version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - RATE_LIMIT_IP=5
      - RATE_LIMIT_TOKEN=10
      - BLOCK_DURATION=300
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
